name: cou_auction_house
version: 0.1.4
description: A polymer component that encapsulates the functionality needed for the game's auction house

dependencies:
  browser: ">=0.10.0+2 <0.11.0"
  polymer: ">=0.16.1+4 <0.17.0"
  core_elements: ">=0.7.1+2 <0.8.0"
  paper_elements: ">=0.7.1 <0.8.0"
  redstone_mapper: ">=0.1.13 <0.2.0"
  intl: ">=0.12.2 <0.13.0"
  pump:
    git:
      ref: master
      url: git://github.com/ppvk/pump.git
  cou_toolkit:
    git:
      ref: master
      url: git://github.com/ChildrenOfUr/cou_toolkit.git

transformers:
- redstone_mapper
- polymer:
    entry_points: web/index.html